feat(train): support rampup batch_size
InternLM/InternLM pull request #493
Opened 2023-11-10 11:06 UTC by SolenoidWGT

## Motivation && Modification
Support rampup batch_size or variable batch size.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-11-13 05:10 UTC, YWMditto requested changes

2023-11-13 05:10 UTC, YWMditto commented on internlm/initialize/launch.py
> +        bsz = data.micro_bsz * data.micro_num
micro_bsz 应该不是这样用的，他是给dataset 用的，表示一个packed_length = micro_bsz * seq_len，这里直接就是 bsz = data.micro_num

2023-11-14 10:56 UTC, YWMditto approved these changes

2023-11-16 11:50 UTC, gaoyang07 approved these changes

2023-11-16 11:51 UTC, merged